### ISSUE TITLE
Mark homework 1 exercise 3 of Maria Kamenetsky

### ISSUE THREAD

**Issue by mkamenet3** [mkamenet3/Stat679#3]
Dear Professor,

Please find my homework1, exercise 3 here: https://github.com/mkamenet3/Stat679/commit/0d1974b15ccdb4bd0a34494481da6cbf0b0eeada

@cecileane

Thank you!

Kindly,

Maria

My approach:
- Similar to exercises 1 and 2, where I created intermediate files and then deleted them. 
- For the comparisons, I had to again use the weird sed syntax and do some replacements due to the fact that I downloaded the 'bc' command externally for cygwin. From what I gathered online, this was the workaround to get it to work. For the comparisons, I extract the list of loglikelihoods for each file, cast to numeric, and then compare to preset targets (3460, 3450, and 3440, respectively). If it is true, it returns a 1, if not it returns a 0. I then sum over those iterations for the loglikelihoods per file and export into csv.

**Comment by mkamenet3** [comment]
Hello Professor! I fixed a bug I found at the end of class and added an if/else statement to handle the exception. Link to latest commit: https://github.com/mkamenet3/Stat679/tree/c3d815b04029c73652c108d2c58534bc83cadf1a

Thank you (and sorry about that)!

@cecileane

**Comment by cecileane** [comment]
Thanks Maria! This is my way of asking Yijing (@IcecreamWine) and Jason (@kunchieh) to try your script and provide feedback on it.

**Comment by kunchieh** [comment]
Hi Maria @mkamenet3 @cecileane ,

You did a good job. The presentation of the  comments on the top of the script which helps the user what the script do, and all other comments does describe how it works. The script is clear and easy to understand. And I have only some suggestions:
First, use another script inside the script is not good for reader or future modifier, especially when the script name does not explain itself. People need to download the other script, put them into the right folder (script/) and might need to open it to understand what it works. I also took a a look of your summarizeSNaQres.sh, and it's not that long, so I will recommend you to directly copy-paste the code to your new script.
Next, in order to run your script, you need to move both "log/" and "out/" folder into a new folder called "data". What I would suggest is to run the script inside the folder which contains both "log/" and "out/" folder and change FILES=`find data/log -name "*.???"` into FILES=`find log -name "*.???"`. Also we need to make sure that it does not have any other files in the folder.
Last thing is create another documents is not that good with reasonably common name is not that good: it might erase some existing files which is for other purpose.  And rm output/*.csv might erase some existing files as well.
Overall, you did a really good job. The script is nice, clear, and easy to understand. Keep this performance :)

Jason

**Comment by cecileane** [comment]
Hi Jason, I didn't quite understand your concerns about the directory structure, because if all scripts are run from the `hw1/` directory, all goes well. Maria's readme files (and comments inside scripts) do say how to run the scripts (`source scripts/xxx`) from `hw1`, so if these instructions are followed, there is no need to move `log/` or `out/` folders. Perhaps I misunderstood your concern.

Also, the repository ships with the normalizing script, so assuming the availability of this normalizing script inside the summary script looks fine to me. 

I agree that the last line `rm output/*.csv` is dangerous. In this command, it would be safer to list exactly those temporary files that were created by the script.

Finally: you should uncomment the lines `set -e`, `set -u` and `set -o pipefail`. Otherwise, they are ignored by the shell!

**Comment by yijingli676** [comment]
Hi Maria,

Excellent work. It is great that you make clear descriptions of all folders in `hw1/` and emphasize the working directory. All your readme.md files are pretty clear. But it seems that you did not document how to use your scripts and I did not know how to run cygwin on Mac. I use `bash` or `source` to run your scripts but neither did they work on my laptop. I may need more advice on this..
And I see your script. It is clear and easy to understand. It is smart that you use `awk` but it would be useful if you practice more `sed` and _extended_ regular expressions. I notice that you did exercise 2 & 3 separately and merged them into one which was clever and convenient. But it would be great if you find a way to build this summary with a single loop instead of 2 loops. In your `output/` folder it also contains another `summaryFiles` folder and I do not get the point here..

Yijing

**Comment by mkamenet3** [comment]
@kunchieh @cecileane @IcecreamWine 
Thank you all for your comments and suggestions! I made revisions to reflect them.  I initially had the **output** folder contain **summaryFiles** as a failsafe so that there should be no .csv files in just **output** and I could delete everything floating around in there. Those are the csv's I was creating and then deleting. The files I wanted to keep were instead sent to **output/summaryFiles**. However, I realize now this was way more complicated than it needed to be - sorry about that! I also see that `rm *.csv` is dangerous in any context so I changed the code to instead specify the files being deleted.

Thank you again for the comments and taking time to review. 

Kindly,

Maria
