### ISSUE TITLE
please check hw2

### ISSUE THREAD

**Issue by mkamenet3** [mkamenet3/Stat679#6]
Dear Professor,
@cecileane

Please find here the link to my latest working commit for hw2:  aadd16f8de4cfa01ba26449a2d0efb8322daf4f2

I was trying to edit the readme and test the code using python from the command line, and then I think I broke things. I was working on a branch and uploaded a commit. Realized some of my changes were wrong so I wanted to only keep the readme changes and switch back. Then when I went back to master, it still had the new/wrong changes (I was also editing in vim and jupyter notebook simultaneously while debugging :/ ). So then I tried to pull from github the original of everything and it said everything was up to date. Sorry!

The code worked in jupyter notebook but I haven't been able to add anything to it for a bit.

Sorry!

Kindly,

Maria

**Comment by mkamenet3** [comment]
Oops! Made some last minute changes - latest commit here: 4ff6d518a58a2227b3f4cf0be2eb5ab20cf09524

@cecileane

(Sorry about that!)

**Comment by cecileane** [comment]
Hi Maria,

Very nice job! Your work was easy to go through. More details below.

## overall presentation

I like that you organized your project with different folders for your script and input/output data files. I also like that you indicated with version of Python was used to develop the code. Your readme file clearly explains how to use your script. You hard-coded the file names, but only in one place (your function can use any file name), and you clearly explains how the user could change the code to use different file names.

You could make better use of markdown style. For example, you wrote this to link to the data source:

    \url{https://github.com/UWMadison-computingtools/coursedata}

This is great for a LaTeX document, but with markdown you should write this (for instance):

    [here](https://github.com/UWMadison-computingtools/coursedata)

and it will look like this: [here](https://github.com/UWMadison-computingtools/coursedata)

For the script name you wrote this: " $hw2_script.py$ ", and a better choice would have been to write this: " \`hw2_script.py\` ", to make it look like this: `hw2_script.py`

## running your script

The check to (not) overwrite an existing output file did not work always. It worked as intended when the `output` folder contained a unique file `merged_output.csv`, and answering `y` worked (`'y'` was not necessary for me):

```shell
$ python scripts/hw2_script.py
everything ran without error for data/waterTemperature.csv
everything ran without error for data/energy.csv
File already exists in directory and will be overwritten
Press 'y' to proceed or 'n' to abort: y
y
Ok, old file overwritten by new file
None
```

and file `merged_output.csv` was overwritten. By the way, the screen output "None" comes from your command to print to result of your `reformat_twofiles` function, but this function returns nothing, so python prints "None".

But when the `output` folder contained another file named `maria.csv` (for instance), the script did not detect that file `merged_output.csv` existed already:

```shell
$ ls output/
maria.csv		merged_output.csv
$ python scripts/hw2_script.py
everything ran without error for data/waterTemperature.csv
everything ran without error for data/energy.csv
Creating output.csv
None
```

and file `merged_output.csv` was overwritten with no warning:

```shell
$ git diff
diff --git a/hw2/output/merged_output.csv b/hw2/output/merged_output.csv
index 2a6c080..0adeb5d 100755
--- a/hw2/output/merged_output.csv
+++ b/hw2/output/merged_output.csv
@@ -1,364 +1,364 @@
-No. , DateTime , WaterTemp , Energy
-1 , 07/29/16 10:26:34 AM , 72.86 ,
...
+No. , DateTime , WaterTemp , Energy
+1 , 07/29/16 10:26:34 AM , 72.86 ,
```

(the new output file had an extra space at the end of each line, hard to see here!). The issue comes from your `while` loop starting on line 71:

```python
file = [fout.split('/')[-1]]
while os.listdir("output/") == file:
    warning = "File already exists in directory and will be overwritten"
    ...
```

The value of `os.listdir("output/")` is the list `['maria.csv', 'merged_output.csv']`, so it's not equal to the value of `file` (which is `'merged_output.csv'`), the `while` condition is False and the script exits this loop immediately.

Also, the second run printed a message about an outdated file name `output.csv`. It is good practice to define a variable for input/output file names from the start, even when these names are hard-coded at first. When it's time to change them or to get them from arguments, we only have to change them in one place and no bugs are introduced.

The output file had extra spaces, unfortunately. Commas are used to separate columns, so there is no need for spaces to separate the cells. Any space will be taken as being part of a cell (by other software like R trying to open & interpret the csv file). For example, your output file has these lines:

    12 , 07/29/16 09:26:34 PM , 73.53 ,
    13 , 07/29/16 10:26:34 PM , 73.27 ,
    14 , 07/29/16 11:26:34 PM , 73.45 , 9.468
    15 , 07/30/16 12:26:34 AM , 72.30 ,

The first cell has "12 ", so R would interpret this as a string: 1, 2, and a space. These extra spaces will be in the way for follow-up analyses. It would be very easy to fix (line 81).

## about your code

It would have been best to break the problem down with several functions.
You have a good use of the datetime module, of list comprehension, and good variable names in general. You should put more comments inside your code, to explain more about what it does. Good checking of the assumption that energy values are recorded at midnight.

You can go ahead and close this issue now.

**Comment by mkamenet3** [comment]
@cecileane 

Thank you very much for your feedback and advice! I will try and integrate those changes shortly.

-Maria

**Comment by cecileane** [comment]
oh you don't need to make any changes: my feedback was just informational, hoping that it might help make your future code/doc better :)
